services:
  add-service:
    build:
      context: .
      dockerfile: AddService/Dockerfile
    image: tobias/calculator-add:$BUILD_NUMBER
    deploy:
      replicas: 3
  subtract-service:
    build:
      context: .
      dockerfile: SubtractService/Dockerfile
    image: tobias/calculator-subtract:$BUILD_NUMBER
    deploy:
      replicas: 3

  calculation-service:
    build:
      context: .
      dockerfile: CalculationService/Dockerfile
    image: tobias/calculator-calculation:$BUILD_NUMBER
    depends_on:
      - add-service
      - subtract-service
      - calculation-history-service
  calculator-service:
    build:
      context: .
      dockerfile: CalculatorGUIService/Dockerfile
    image: tobias/calculator-calculator:$BUILD_NUMBER
    depends_on:
      - calculation-service
    ports:
      - 8080:80

    
  seq:
    image: datalust/seq
    ports:
      - "5341:5341"
      - "5342:80"
    volumes:
      - rps_seq_data:/data
    environment:
      - ACCEPT_EULA=Y

  
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    environment:
      - STORAGE_TYPE=mysql
      - MYSQL_HOST=zipkin-storage
      - MYSQL_USER=zipkin
      - MYSQL_PASS=zipkin
      - MYSQL_DB=zipkin
    depends_on:
      - zipkin-storage
 
  
  zipkin-storage:
    image: openzipkin/zipkin-mysql
    ports: 
      - "3306:3306"
    volumes:
      - zipkin_data:/mysql/data

    
  calculation-history-service:
    build:
      context: .
      dockerfile: CalculationHistoryService/Dockerfile
    image: tobias/calculator-history:$BUILD_NUMBER
    depends_on:
      - cache-db
    deploy:
      replicas: 2
 
        
  cache-db:
    image: "mysql"
    environment:
      MYSQL_DATABASE: "cache-database"
      MYSQL_USER: "div-cache"
      MYSQL_PASSWORD: "C@ch3d1v"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"

    
volumes:
  rps_seq_data:
  zipkin_data:

 
