services:
  add-service:
    build:
      context: .
      dockerfile: AddService/Dockerfile
    deploy:
      replicas: 2
  subtract-service:
    build:
      context: .
      dockerfile: SubtractService/Dockerfile
    deploy:
      replicas: 2
  calculation-service:
    build:
      context: .
      dockerfile: CalculationService/Dockerfile
    depends_on:
      - add-service
      - subtract-service
  calculator-service:
    build:
      context: .
      dockerfile: CalculatorGUIService/Dockerfile
    depends_on:
      - calculation-service
    ports:
      - 8080:80
    
  seq:
    image: datalust/seq
    ports:
      - 5341:5341
      - 5342:5342
    volumes:
      - rps_seq_data:/data
    environment:
      - ACCEPT_EULA=Y
  
  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
    environment:
      - STORAGE_TYPE=mysql
      - MYSQL_HOST=zipkin-storage
      - MYSQL_USER=zipkin
      - MYSQL_PASS=zipkin
      - MYSQL_DB=zipkin
    depends_on:
      - zipkin-storage
  
  zipkin-storage:
    image: openzipkin/zipkin-mysql
    ports: 
      - 3306:3306
    volumes:
      - zipkin_data:/mysql/data
    
volumes:
  rps_seq_data:
  zipkin_data:
 
